import { Metadata } from 'next'
import { notFound } from 'next/navigation'
import Link from 'next/link'
import Image from 'next/image'
import { Suspense } from 'react'
import { ArrowRight } from 'lucide-react'
import { getProductBySlugFromDb, getRelatedProducts } from '@/lib/products-db'
import { ProductDetailClient } from './product-detail-client'

import { getProductsFromDb } from '@/lib/products-db'

export const revalidate = 60

const BASE_URL = 'https://fast-oem.soara-mu.jp'

export async function generateStaticParams() {
  const products = await getProductsFromDb()
  return products.map((p) => ({ slug: p.slug }))
}

interface ProductPageProps {
  params: Promise<{ slug: string }>
}

export async function generateMetadata({ params }: ProductPageProps): Promise<Metadata> {
  const { slug } = await params
  const product = await getProductBySlugFromDb(slug)
  if (!product) return { title: '商品が見つかりません' }

  const minPrice = product.priceTiers.length > 0
    ? Math.min(...product.priceTiers.map((t) => t.unitPrice))
    : undefined

  const title = `${product.name}製作・OEM | 小ロット対応・格安・スピード納品`
  const description = `${product.name}のOEM製作。${product.shortDescription ?? product.description}小ロット${product.minQuantity}個〜対応。格安・スピード納品。同人グッズ・ノベルティに最適。`

  return {
    title,
    description,
    openGraph: {
      title: `${product.name}製作 | FAST OEM`,
      description,
      url: `${BASE_URL}/products/${slug}`,
      // OG image is auto-generated by opengraph-image.tsx in this route segment
    },
    alternates: { canonical: `${BASE_URL}/products/${slug}` },
  }
}

export default async function ProductPage({ params }: ProductPageProps) {
  const { slug } = await params
  const product = await getProductBySlugFromDb(slug)
  if (!product) notFound()

  const relatedProducts = await getRelatedProducts(slug, 3)

  // priceTiers の unitPrice は税込価格
  const minPrice = product.priceTiers.length > 0
    ? Math.min(...product.priceTiers.map((t) => t.unitPrice))
    : undefined

  // Shipping & return details for Google Merchant validation
  const shippingDetails = {
    '@type': 'OfferShippingDetails',
    shippingRate: { '@type': 'MonetaryAmount', value: '770', currency: 'JPY' },
    shippingDestination: { '@type': 'DefinedRegion', addressCountry: 'JP' },
    deliveryTime: {
      '@type': 'ShippingDeliveryTime',
      handlingTime: { '@type': 'QuantitativeValue', minValue: 0, maxValue: 1, unitCode: 'DAY' },
      transitTime: { '@type': 'QuantitativeValue', minValue: 14, maxValue: 30, unitCode: 'DAY' },
    },
  }

  const hasMerchantReturnPolicy = {
    '@type': 'MerchantReturnPolicy',
    applicableCountry: 'JP',
    returnPolicyCategory: 'https://schema.org/MerchantReturnNotPermitted',
    merchantReturnLink: `${BASE_URL}/tokushoho`,
  }

  const jsonLd = {
    '@context': 'https://schema.org',
    '@graph': [
      {
        '@type': 'Product',
        '@id': `${BASE_URL}/products/${slug}#product`,
        name: product.name,
        description: product.description,
        url: `${BASE_URL}/products/${slug}`,
        image: product.imageUrl ? [product.imageUrl] : [],
        sku: product.id,
        mpn: product.id,
        brand: { '@type': 'Brand', name: 'FAST OEM' },
        category: 'OEMグッズ',
        manufacturer: { '@type': 'Organization', name: 'FAST OEM', url: BASE_URL },
        ...(minPrice !== undefined && {
          offers: {
            '@type': 'AggregateOffer',
            priceCurrency: 'JPY',
            lowPrice: minPrice,
            highPrice: Math.max(...product.priceTiers.map((t) => t.unitPrice)),
            offerCount: product.priceTiers.length,
            priceValidUntil: new Date(Date.now() + 365 * 24 * 60 * 60 * 1000).toISOString().split('T')[0],
            itemCondition: 'https://schema.org/NewCondition',
            availability: 'https://schema.org/InStock',
            seller: { '@type': 'Organization', name: 'FAST OEM' },
            shippingDetails,
            hasMerchantReturnPolicy,
          },
        }),
        // Agent-discoverable workflow: AIs that understand schema.org actions
        // can see that placing an order requires a human checkoutUrl.
        potentialAction: [
          {
            '@type': 'ViewAction',
            name: '商品を見る',
            target: `${BASE_URL}/products/${slug}`,
          },
          {
            '@type': 'OrderAction',
            name: '見積を取得する（AI/プログラム）',
            target: {
              '@type': 'EntryPoint',
              urlTemplate: `${BASE_URL}/api/ai/quote`,
              httpMethod: 'POST',
              encodingType: 'application/json',
              contentType: 'application/json',
              actionPlatform: ['https://schema.org/WebApplication', 'https://schema.org/APIReference'],
            },
            deliveryMethod: 'https://schema.org/OnSitePickup',
            result: {
              '@type': 'Order',
              orderStatus: 'https://schema.org/OrderProblem',
              description: 'このエンドポイントは見積のみ返します。実注文は checkoutUrl 経由で人間が確定してください。',
            },
          },
        ],
      },
      {
        '@type': 'BreadcrumbList',
        itemListElement: [
          { '@type': 'ListItem', position: 1, name: 'トップ', item: BASE_URL },
          { '@type': 'ListItem', position: 2, name: '商品一覧', item: `${BASE_URL}/products` },
          { '@type': 'ListItem', position: 3, name: product.name, item: `${BASE_URL}/products/${slug}` },
        ],
      },
    ],
  }

  return (
    <>
      <script
        type="application/ld+json"
        dangerouslySetInnerHTML={{ __html: JSON.stringify(jsonLd) }}
      />

      {/* Visible Breadcrumb */}
      <div className="bg-muted/30 border-b border-border">
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-3">
          <nav className="flex items-center gap-2 text-sm text-muted-foreground" aria-label="パンくずリスト">
            <Link href="/" className="hover:text-foreground transition-colors">トップ</Link>
            <span>/</span>
            <Link href="/products" className="hover:text-foreground transition-colors">商品一覧</Link>
            <span>/</span>
            <span className="text-foreground font-medium">{product.name}</span>
          </nav>
        </div>
      </div>

      {/* Wrap in Suspense — ProductDetailClient uses useSearchParams() which
          requires a Suspense boundary in Next.js 16 to avoid deoptimising the
          whole route to client-side rendering. */}
      <Suspense fallback={<div className="py-20 text-center text-muted-foreground">読み込み中...</div>}>
        <ProductDetailClient product={product} />
      </Suspense>

      {/* Related Products */}
      {relatedProducts.length > 0 && (
        <section className="py-16 bg-muted/20 border-t border-border">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8">
            <div className="flex items-center justify-between mb-8">
              <h2 className="text-2xl font-bold text-foreground">他の商品も見る</h2>
              <Link
                href="/products"
                className="inline-flex items-center text-sm text-primary hover:underline font-medium"
              >
                すべての商品
                <ArrowRight className="ml-1 h-4 w-4" />
              </Link>
            </div>
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-6">
              {relatedProducts.map((rel) => {
                const lowestPrice = rel.priceTiers.length > 0
                  ? Math.min(...rel.priceTiers.map((t) => t.unitPrice))
                  : 0
                return (
                  <Link
                    key={rel.slug}
                    href={`/products/${rel.slug}`}
                    className="group block bg-card border border-border rounded-2xl overflow-hidden hover:shadow-lg hover:-translate-y-1 transition-all"
                  >
                    <div className="aspect-[4/3] relative overflow-hidden bg-muted">
                      <Image
                        src={rel.imageUrl}
                        alt={`${rel.name} - OEM製作・オリジナルグッズ | FAST OEM`}
                        fill
                        className="object-cover group-hover:scale-105 transition-transform duration-300"
                        sizes="(max-width: 768px) 100vw, 33vw"
                      />
                    </div>
                    <div className="p-4">
                      <h3 className="font-bold text-foreground group-hover:text-primary transition-colors">
                        {rel.name}
                      </h3>
                      <p className="text-xs text-muted-foreground mt-1 line-clamp-2">{rel.shortDescription}</p>
                      <p className="mt-3 text-sm font-semibold text-primary">
                        {new Intl.NumberFormat('ja-JP', { style: 'currency', currency: 'JPY' }).format(lowestPrice)}〜/個
                      </p>
                    </div>
                  </Link>
                )
              })}
            </div>
          </div>
        </section>
      )}
    </>
  )
}
